---
abstract: 'Catalyst based application'
author:
  - 'Catalyst developer'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDT-Server
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80016
  Catalyst::View::Mason: 0
  DBD::Pg: 0
  Data::Dumper: 0
  Digest::SHA: 0
  Fey::DBIManager: 0
  Fey::Loader: 0
  Fey::ORM: 0
  GD::SecurityImage: 0
  Module::Pluggable: 0
  Moose: 0
  MooseX::ClassAttribute: 0
  MooseX::Types: 0
  PDT::Config: 0
  YAML::Syck: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
